services:
  - type: web
    name: summarizer-backend
    runtime: docker
    plan: free
    region: oregon
    repo: https://github.com/JKristilere/Smart-Summarizer
    branch: master
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      # Database connection
      - key: DATABASE_URI
        fromDatabase:
          name: summarizer-db
          property: connectionString
      
      # API Keys (set these in Render dashboard)
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false

    healthCheckPath: /health
# services:
#   - type: web
#     name: summarizer-backend
#     runtime: docker
#     plan: free
#     region: oregon
#     repo: https://github.com/JKristilere/Smart-Summarizer
#     branch: master
#     rootDir: backend
#     dockerfilePath: ./Dockerfile
#     dockerContext: .
#     envVars:
#       - key: DATABASE_URI
#         fromDatabase:
#           name: summarizer-db
#           property: connectionString

#       - key: GROQ_API_KEY
#         sync: false
#       - key: CHROMA_API_KEY
#         sync: false
#       - key: CHROMA_TENANT
#         sync: false
#       - key: CHROMA_DATABASE
#         sync: false

#     healthCheckPath: /health
